### ISSUE TITLE
Unclosed quote error

### ISSUE THREAD

**Issue by ifrac** [vieron/stylelint-webpack-plugin#11]
I'm having this error. My main.pcss file is importing base.pcss file with only one css rule so it can't be on line 76
```
ERROR in ./~/css-loader!./~/postcss-loader!./~/stylelint/dist!./src/assets/style/main.pcss
C:\forWeb\Workflow\FrontendBoilerplate\src\assets\style\main.pcss:76:24: Unclosed quote

        // Log the rule's severity in the PostCSS result
                       ^
        result.stylelint.ruleSeverities[ruleName] = _lodash2.default.get(secondaryOptions, "severity", "error");

ERROR in ./~/css-loader!./~/postcss-loader!./~/stylelint/dist!./src/assets/style/main.pcss
Module build failed: TypeError: Cannot read property 'toString' of undefined
    at new Input (C:\forWeb\Workflow\FrontendBoilerplate\node_modules\postcss\lib\input.js:31:23)
    at parse (C:\forWeb\Workflow\FrontendBoilerplate\node_modules\postcss\lib\parse.js:22:17)
    at new LazyResult (C:\forWeb\Workflow\FrontendBoilerplate\node_modules\postcss\lib\lazy-result.js:61:24)
    at Processor.process (C:\forWeb\Workflow\FrontendBoilerplate\node_modules\postcss\lib\processor.js:34:16)
    at processCss (C:\forWeb\Workflow\FrontendBoilerplate\node_modules\css-loader\lib\processCss.js:188:11)
    at Object.module.exports (C:\forWeb\Workflow\FrontendBoilerplate\node_modules\css-loader\lib\loader.js:24:2)
 @ ./src/assets/style/main.pcss 4:14-178
```

**Comment by ifrac** [comment]
Ok, found error. It was my fault becouse i added stylelint preLoader.
